.TH GET_CLASS 8
.SH NAME
get_class \- Get classification value
.SH SYNOPSIS
\fBget_class\fR(\fB\-\fIpid_t\fR]\fR)
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH EXAMPLES
.TP 20
.B get_class(50)
# Get the classification value of PID \fI50\fR
.TP 20
.SH DESCRIPTION
.PP
\fIGet_class\fR returns the classification value of the specified process
.SH "SEE ALSO"
.BR set_class (8).
