.TH SET_CLASS 8
.SH NAME
get_class \- Get classification value
.SH SYNOPSIS
\fBset_class\fR(\fB\-\fIpid_t, int\fR]\fR)
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH EXAMPLES
.TP 20
.B set_class(50, 8)
# Set the classification value of PID \fI50\fR to \fI8\fR
.TP 20
.SH DESCRIPTION
.PP
Set_class sets the classification value of the specified process to the specified value.
.SH "SEE ALSO"
.BR get_class (8).
