.TH GETCLASS 1
.SH NAME
getclass \- returns the classification value of a file
.SH SYNOPSIS
\fBget_class\fR [\fIfile\fR] ...\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH EXAMPLES
.TP 20
.B get_class(file)
# Return classification value of \fIfile\fP
.SH DESCRIPTION
.PP
Returns the classification value used for handling file manipulation.
.SH "SEE ALSO"
.BR set_class (1)
